from __future__ import annotations

QUESTION_BANK = {
    "Q1": {
        "concept": "SELECT",
        "task": "Retrieve all columns and rows from the Customers table.",
        "expected_thinking": [
            "Identify the table: Customers",
            "Use SELECT * to return all columns",
        ],
        "teaching_focus": "Understand that SELECT * returns all columns from one table.",
        "common_mistake": "Introducing filtering or selecting specific columns too early.",
        "syntax_pattern": "SELECT * FROM Customers;",
        "what_changes_from_previous": "This is the starting question. Focus only on selecting data from one table.",
        "allowed_feedback_scope": [
            "SELECT",
            "SELECT *",
            "all columns",
            "Customers table",
            "rows and columns",
        ],
        "explanation_keywords": [
            "all columns",
            "customers",
            "table",
            "rows",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q2": {
        "concept": "Selecting columns",
        "task": "Retrieve CustomerName and City from the Customers table.",
        "expected_thinking": [
            "Replace * with specific column names",
        ],
        "teaching_focus": "Understand that SELECT can return only chosen columns instead of every column.",
        "common_mistake": "Using SELECT * instead of listing the required columns.",
        "syntax_pattern": "SELECT CustomerName, City FROM Customers;",
        "what_changes_from_previous": "Instead of returning all columns, now return only the columns requested.",
        "allowed_feedback_scope": [
            "specific columns",
            "CustomerName",
            "City",
            "SELECT column names",
            "do not use * for this question",
        ],
        "explanation_keywords": [
            "customername",
            "city",
            "specific columns",
            "customers",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q3": {
        "concept": "WHERE",
        "task": "Retrieve all customers from Germany.",
        "expected_thinking": [
            "Filter rows using Country = 'Germany'",
        ],
        "teaching_focus": "Understand that WHERE filters rows by condition.",
        "common_mistake": "Selecting the right table but not filtering rows.",
        "syntax_pattern": "SELECT * FROM Customers WHERE Country = 'Germany';",
        "what_changes_from_previous": "Now keep the same table, but add a condition to filter which rows appear.",
        "allowed_feedback_scope": [
            "WHERE",
            "filter rows",
            "Country = 'Germany'",
            "condition",
        ],
        "explanation_keywords": [
            "where",
            "germany",
            "filter",
            "customers",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q4": {
        "concept": "AND / OR",
        "task": "Retrieve all customers from Germany OR France.",
        "expected_thinking": [
            "Combine conditions with OR",
        ],
        "teaching_focus": "Understand how OR combines multiple conditions in a WHERE clause.",
        "common_mistake": "Writing one condition correctly but not repeating the column name in the second condition.",
        "syntax_pattern": "SELECT * FROM Customers WHERE Country = 'Germany' OR Country = 'France';",
        "what_changes_from_previous": "Instead of one filter condition, now combine two possible values.",
        "allowed_feedback_scope": [
            "OR",
            "multiple conditions",
            "repeat column name",
            "WHERE with OR",
        ],
        "explanation_keywords": [
            "or",
            "germany",
            "france",
            "condition",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q5": {
        "concept": "ORDER BY",
        "task": "Retrieve all customers and sort them by CustomerName.",
        "expected_thinking": [
            "Sort results using ORDER BY",
        ],
        "teaching_focus": "Understand that ORDER BY controls the sorting of returned rows.",
        "common_mistake": "Returning the correct rows but not applying sorting.",
        "syntax_pattern": "SELECT * FROM Customers ORDER BY CustomerName;",
        "what_changes_from_previous": "Now focus on result order, not filtering.",
        "allowed_feedback_scope": [
            "ORDER BY",
            "sort",
            "CustomerName",
            "sorting rows",
        ],
        "explanation_keywords": [
            "order by",
            "sort",
            "customername",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q6": {
        "concept": "DISTINCT",
        "task": "Retrieve a list of unique countries from the Customers table.",
        "expected_thinking": [
            "Use DISTINCT to remove duplicates",
        ],
        "teaching_focus": "Understand that DISTINCT removes duplicate values from a result set.",
        "common_mistake": "Selecting the correct column but leaving repeated values in the output.",
        "syntax_pattern": "SELECT DISTINCT Country FROM Customers;",
        "what_changes_from_previous": "Now the goal is not all rows, but unique values only.",
        "allowed_feedback_scope": [
            "DISTINCT",
            "unique values",
            "Country",
            "remove duplicates",
        ],
        "explanation_keywords": [
            "distinct",
            "unique",
            "country",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q7": {
        "concept": "COUNT",
        "task": "Count the total number of orders in the Orders table.",
        "expected_thinking": [
            "Use COUNT() to aggregate",
        ],
        "teaching_focus": "Understand that COUNT() returns the number of rows or values being counted.",
        "common_mistake": "Selecting rows instead of aggregating them into one total.",
        "syntax_pattern": "SELECT COUNT(*) FROM Orders;",
        "what_changes_from_previous": "Now the goal is a single summary value instead of a list of rows.",
        "allowed_feedback_scope": [
            "COUNT",
            "aggregate",
            "single total",
            "Orders table",
        ],
        "explanation_keywords": [
            "count",
            "orders",
            "total",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q8": {
        "concept": "GROUP BY",
        "task": "Count how many customers are in each country.",
        "expected_thinking": [
            "Use COUNT() and GROUP BY Country",
        ],
        "teaching_focus": "Understand that GROUP BY creates one row per group before aggregation.",
        "common_mistake": "Using COUNT() without grouping, which produces only one overall total.",
        "syntax_pattern": "SELECT Country, COUNT(*) FROM Customers GROUP BY Country;",
        "what_changes_from_previous": "Instead of one total, now produce one count for each country.",
        "allowed_feedback_scope": [
            "GROUP BY",
            "Country",
            "one row per country",
            "COUNT by group",
        ],
        "explanation_keywords": [
            "group by",
            "country",
            "count",
            "each country",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q9": {
        "concept": "HAVING",
        "task": "Show only countries with more than 5 customers.",
        "expected_thinking": [
            "Use HAVING with COUNT()",
        ],
        "teaching_focus": "Understand that HAVING filters grouped results after aggregation.",
        "common_mistake": "Trying to use WHERE instead of HAVING to filter aggregate results.",
        "syntax_pattern": "SELECT Country, COUNT(*) FROM Customers GROUP BY Country HAVING COUNT(*) > 5;",
        "what_changes_from_previous": "Now filter grouped results after the GROUP BY step.",
        "allowed_feedback_scope": [
            "HAVING",
            "filter grouped results",
            "COUNT(*) > 5",
            "after aggregation",
        ],
        "explanation_keywords": [
            "having",
            "count",
            "more than 5",
            "country",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q10": {
        "concept": "JOIN",
        "task": "Retrieve CustomerName and OrderID for all customers and their orders.",
        "expected_thinking": [
            "Join Customers and Orders on CustomerID",
        ],
        "teaching_focus": "Understand that JOIN combines related data across tables using a shared key.",
        "common_mistake": "Using the correct tables but not joining on the right key.",
        "syntax_pattern": "SELECT Customers.CustomerName, Orders.OrderID FROM Customers JOIN Orders ON Customers.CustomerID = Orders.CustomerID;",
        "what_changes_from_previous": "Now combine data from two related tables instead of working within one table.",
        "allowed_feedback_scope": [
            "JOIN",
            "Customers and Orders",
            "CustomerID",
            "shared key",
            "combine tables",
        ],
        "explanation_keywords": [
            "join",
            "customers",
            "orders",
            "customerid",
            "orderid",
        ],
        "new_concept": True,
        "is_multi_concept": False,
    },
    "Q11": {
        "concept": "JOIN + GROUP BY + COUNT",
        "task": "Determine how many orders each customer has made.",
        "expected_thinking": [
            "Join Customers and Orders",
            "Count orders",
            "Group by customer",
        ],
        "teaching_focus": "Integrate joining tables, counting records, and grouping results into one query.",
        "common_mistake": "Joining correctly but forgetting GROUP BY, or counting without grouping by customer.",
        "syntax_pattern": "SELECT Customers.CustomerName, COUNT(Orders.OrderID) FROM Customers JOIN Orders ON Customers.CustomerID = Orders.CustomerID GROUP BY Customers.CustomerName;",
        "what_changes_from_previous": "This is the capstone question: combine joining, counting, and grouping in one query.",
        "allowed_feedback_scope": [
            "JOIN",
            "GROUP BY",
            "COUNT",
            "CustomerName",
            "orders per customer",
            "one row per customer",
        ],
        "explanation_keywords": [
            "join",
            "group by",
            "count",
            "orders",
            "customer",
        ],
        "new_concept": True,
        "is_multi_concept": True,
    },
}

QUESTION_ORDER = list(QUESTION_BANK.keys())